name: "Test"
on:
  push:
    branches:
      - develop
      - master
      - release/*
      - "*-stable"
  pull_request:
    branches:
      - "*"

jobs:
  main:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep -v "GITHUB_TOKEN"
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
          ref: ${{ $GITHUB_HEAD_REF ? "refs/head/$GITHUB_HEAD_REF" : $GITHUB_REF }}
      - run: foobar