name: "Test"
on:
  push:
    branches:
      - develop
      - master
      - release/*
      - "*-stable"
  pull_request:
    branches:
      - "*"

jobs:
  main:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep -v "GITHUB_TOKEN"
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
      - run: ./.github/upload_coverage.sh "patatas!" $GITHUB_EVENT_PATH
        if: "!startsWith(github.head_ref, 'refs/heads/l10n_')"
      - run: cat $GITHUB_EVENT_PATH
        if: "!startsWith(github.head_ref, 'l10n_')"
      - run: foobar