name: "[CI] Core"
on:
  push:
    branches:
      - develop
      - master
      - release/*
      - "*-stable"
  pull_request:
    branches:
      - "*"

jobs:
  main:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep -v "GITHUB_TOKEN"
      - run: foobar